use laptop_borrowing;

select * from laptops;
SELECT * FROM laptops LIMIT 10 OFFSET 0;

-- AVAILABLE LAPTOPS
SELECT * FROM laptops l WHERE l.laptop_id NOT IN (SELECT br.laptop_id FROM borrow_records br WHERE br.return_date IS NULL ) LIMIT 10 OFFSET 0;

-- IN USE LAPTOPS
SELECT * FROM laptops l WHERE l.laptop_id IN (SELECT br.laptop_id FROM borrow_records br WHERE br.return_date IS NULL ) LIMIT 10 OFFSET 0;


INSERT INTO laptops(product_name, product_os, battery_health) VALUES
('MacBook Pro 13"', 'MacOS', 95),
('Dell XPS 15', 'Windows', 87),
('HP Spectre x360', 'Windows', 92),
('Lenovo ThinkPad X1', 'Windows', 85),
('MacBook Air M1', 'MacOS', 98),
('Asus ZenBook 14', 'Windows', 80),
('Microsoft Surface Laptop 4', 'Windows', 89),
('Acer Swift 3', 'Windows', 78),
('MacBook Pro 16"', 'MacOS', 91),
('Dell Inspiron 15', 'Windows', 82),
('HP Envy 13', 'Windows', 88),
('Lenovo Yoga C940', 'Windows', 84),
('MacBook Pro 14"', 'MacOS', 96),
('Asus ROG Zephyrus', 'Windows', 76),
('Microsoft Surface Pro 8', 'Windows', 90),
('Acer Predator Helios', 'Windows', 75),
('Dell Latitude 7420', 'Windows', 86),
('HP Pavilion 15', 'Windows', 79),
('Lenovo IdeaPad 5', 'Windows', 83),
('MacBook Air M2', 'MacOS', 97),
('Asus VivoBook 15', 'Windows', 81),
('Microsoft Surface Laptop Go', 'Windows', 88),
('Acer Aspire 5', 'Windows', 77),
('Dell Alienware m15', 'Windows', 74),
('HP EliteBook 840', 'Windows', 89),
('Lenovo Legion 5', 'Windows', 76),
('MacBook Pro 13" M2', 'MacOS', 94),
('Asus ExpertBook B9', 'Windows', 87),
('Microsoft Surface Book 3', 'Windows', 85),
('Acer Spin 5', 'Windows', 82),
('Dell Precision 5560', 'Windows', 83),
('HP ProBook 450', 'Windows', 80),
('Lenovo ThinkPad T14', 'Windows', 86),
('MacBook Air 13"', 'MacOS', 93),
('Asus Chromebook Flip', 'Linux', 91),
('Microsoft Surface Laptop Studio', 'Windows', 84),
('Acer TravelMate P6', 'Windows', 79),
('Dell Vostro 15', 'Windows', 78),
('HP ZBook Firefly', 'Windows', 85),
('Lenovo Flex 5', 'Windows', 82),
('MacBook Pro 16" M1', 'MacOS', 95),
('Asus TUF Gaming', 'Windows', 73),
('Microsoft Surface Go 3', 'Windows', 89),
('Acer ConceptD 7', 'Windows', 81),
('Dell XPS 13', 'Windows', 90),
('HP Omen 15', 'Windows', 75),
('Lenovo ThinkBook 14', 'Windows', 84),
('MacBook Pro 14" M1', 'MacOS', 96),
('Asus ROG Strix', 'Windows', 72),
('Microsoft Surface Laptop 5', 'Windows', 87),
('Acer Nitro 5', 'Windows', 74),
('Dell G15', 'Windows', 76),
('HP Stream 14', 'Windows', 80),
('Lenovo IdeaPad Gaming 3', 'Windows', 77),
('MacBook Air 15"', 'MacOS', 94),
('Asus ExpertCenter', 'Linux', 83),
('Microsoft Surface Duo', 'Windows', 86),
('Acer Enduro N7', 'Windows', 78),
('Dell OptiPlex 7080', 'Linux', 85),
('HP Chromebook 14', 'Linux', 89),
('Lenovo ThinkPad E15', 'Windows', 82),
('MacBook Pro 13" M1', 'MacOS', 97),
('Asus BR1100', 'Windows', 81),
('Microsoft Surface Laptop 3', 'Windows', 84),
('Acer Extensa 15', 'Windows', 79),
('Dell Inspiron 14', 'Windows', 83),
('HP Elite Dragonfly', 'Windows', 88),
('Lenovo Yoga 9i', 'Windows', 85),
('MacBook Pro 16" M2', 'MacOS', 95),
('Asus ZenBook Duo', 'Windows', 80),
('Microsoft Surface Pro 7', 'Windows', 87),
('Acer Swift X', 'Windows', 82),
('Dell Precision 7560', 'Windows', 84),
('HP Spectre 14', 'Windows', 89),
('Lenovo ThinkPad X1 Carbon', 'Windows', 86),
('MacBook Air M1 16GB', 'MacOS', 96),
('Asus ROG Flow', 'Windows', 75),
('Microsoft Surface Laptop 2', 'Windows', 83),
('Acer Chromebook Spin', 'Linux', 90),
('Dell Latitude 5430', 'Windows', 85),
('HP Victus 16', 'Windows', 77),
('Lenovo IdeaPad Flex', 'Windows', 82),
('MacBook Pro 14" M2', 'MacOS', 97),
('Asus ExpertBook P2', 'Windows', 84),
('Microsoft Surface Book 2', 'Windows', 86),
('Acer Spin 3', 'Windows', 81),
('Dell XPS 17', 'Windows', 88),
('HP Pavilion x360', 'Windows', 83),
('Lenovo Legion 7', 'Windows', 76),
('MacBook Air M2 16GB', 'MacOS', 98),
('Asus VivoBook S14', 'Windows', 82),
('Microsoft Surface Go 2', 'Windows', 85),
('Acer Predator Triton', 'Windows', 74),
('Dell Inspiron 16', 'Windows', 84),
('HP EliteBook 830', 'Windows', 87),
('Lenovo ThinkPad P15', 'Windows', 83),
('MacBook Pro 13" 2020', 'MacOS', 93),
('Asus ROG Zephyrus Duo', 'Windows', 75),
('Microsoft Surface Laptop 7', 'Windows', 89),
('Acer Swift 1', 'Windows', 80),
('Dell Precision 3460', 'Linux', 86),
('HP Envy x360', 'Windows', 84),
('Lenovo Yoga C740', 'Windows', 82),
('MacBook Pro 16" 2021', 'MacOS', 94);